version: '3'
services:
  mongodb:
    image: daocloud.io/mongo:3.5
    hostname: localhost
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
