phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
    restart: always
    ports:
        - "8080:80"
    volumes:
        - "./config.user.inc.php:~/docker/phpmyadmin/config.user.inc.php"

