version: "3"
volumes:
  mysql_data:
services:
  db:
    image: mysql/mysql-server
    container_name: mysql4dev
    volumes:
      - "./mysqldb:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3306:3306"
