version: "3"
services:
  db:
    image: mysql
    container_name: mysql4dev
    volumes:
      - "./mysqldb:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
