version: "3"
services:
    mysql_master:
        build:
          context: ./
          dockerfile: master/Dockerfile
        volumes:
            -  "./mysql_master:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
        links:
          - mysql_slave
        ports:
            -  "33060:3306"
        restart: always
        hostname: mysql_master
    mysql_slave:
        build:
          context: ./
          dockerfile: slave/Dockerfile
        volumes:
            -  "./mysql_slave:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            -  "33061:3306"
        restart: always
        hostname: mysql_slave
