version: "2"
services:
  db:
    image: mysql
    container_name: mysql4dev
    volumes:
      - "./mysqldb:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    expose:
      - "3306"  
    ports:
      - "3306:3306"
